/**
 * This file was automatically generated by VersionTag.cmake
 */
#pragma once
#define worldspace2_VERSION_MAJOR			0
#define worldspace2_VERSION_MINOR			0
#define worldspace2_VERSION_PATCH			3
#define worldspace2_VERSION_EXTRA			

// Current worldspace2 version number as a string.
#define worldspace2_VERSION				"0.0.3"

// Current worldspace2 extended version number as a string.
#define worldspace2_VERSION_EXTENDED		"0.0.3"
